#!/usr/bin/env python

import sys
import socket
import datetime
import pyinotify
import functools

# Determine sar filename
sarfile = "/var/log/sa/sa" + str(datetime.date.today().day)

# Open current sar file in binary mode
byteFile = open(sarfile, 'rb')

# Read existing sar data
print "Reading existing sar data. \n"
byteFile.read()

# Read latest sadc update (20248 bytes)
def readUpdate(byteFile):
    latestUpdate = byteFile.read()
    return latestUpdate

# Send sadc update to remote server
def sendUpdate(latestUpdate):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect(("localhost", 3333))
    sendStatus = sock.sendall(latestUpdate)
    sock.close()
    return sendStatus

# inotify function called when sarfile is modified 
def procUpdate(object):
    latestUpdate = readUpdate(byteFile)
    sendStatus = sendUpdate(latestUpdate, newfile)

# setup inotify watch 
wm = pyinotify.WatchManager()
wm.add_watch(sarfile, pyinotify.IN_MODIFY, procUpdate)
notifier = pyinotify.Notifier(wm)
notifier.loop()

# Close sar file
byteFile.close()

